server:
  port: 9092

spring:
  profiles:
    active: prod
  application:
    name: ms2
  data:
    mongodb:
      database: ms2
      host: 192.168.152.130
      port: 27017
      username: mpngo
      password: mongo123456
      authentication-database: admin
  cloud:
    consul:
      host: 192.168.152.130
      port: 8500
      discovery:
        hostname: localhost
        health-check-path: /actuator/health
        instance-id: ${spring.application.name}:${random.value}
        health-check-interval: 20s
  rabbitmq:
    host: 192.168.152.130
    port: 5672
    username: rabbit
    password: rabbit123456