server:
  port: 9090

spring:
  profiles:
    active: prod
  application:
    name: gateway
  cloud:
    consul:
      host: 192.168.152.130
      port: 8500
      discovery:
        hostname: localhost
        health-check-path: /actuator/health
        instance-id: ${spring.application.name}:${random.value}
        health-check-interval: 20s
